import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components";
import { ReactNode } from "react";

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <div className="relative flex min-h-screen flex-col bg-background">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
